#!/bin/bash
#$ -l h_rt=90:00:00     # Specify the hard time limit for the job
#$ -P cui-buchem        # project name
#$ -N b2-collect         # job name
#$ -e b2-gen.err     # error file name
#$ -j y                 # merge console out and error in same file
#$ -V
#$ -pe omp 1            # request parallel env with 8 cores
# -pe mpi_1_tasks_per_node 1    # mpi_12_tasks_per_node 144 will take 12 nodes

module load intel/2018
module load openmpi/3.1.1_intel-2018
module load python3/3.7.3

python calculate_virial.py > vir_temp2.dat 
